'use strict';

/**
 * Builds the single-file Coriolis API bundle (`coriolis-api.js`).
 *
 * Instead of concatenating Coriolis sources with string replacements, we let
 * esbuild resolve the real ES module graph. That keeps imports, tree shaking
 * and name scoping correct and removes the fragile `ModuleUtils.`/`_.`
 * text substitutions entirely.
 */

import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));

const banner = `/**
 * This file is automatically generated by build.mjs.
 * Do not edit it directly; edit src/index.js instead.
 */`;

/**
 * Loads the Coriolis sources with the JSX loader (they ship JSX inside .js
 * files) and fixes a known upstream bug: the standalone `totalJumpRange`
 * helper calls `this.jumpRange(...)`, where `this` is undefined.
 */
const coriolisSources = {
  name: 'coriolis-sources',
  setup(build) {
    build.onLoad(
      { filter: /[\\/]coriolis[\\/]src[\\/].*\.js$/ },
      async (args) => {
        const contents = (
          await fs.promises.readFile(args.path, 'utf8')
        ).replace(/this\.jumpRange\(/g, 'jumpRange(');
        return { contents, loader: 'jsx' };
      }
    );
  },
};

await build({
  absWorkingDir: root,
  entryPoints: ['src/index.js'],
  outfile: 'coriolis-api.js',
  bundle: true,
  platform: 'node',
  target: 'node18',
  format: 'cjs',
  sourcemap: false,
  legalComments: 'none',
  banner: { js: banner },
  plugins: [coriolisSources],
  // The Coriolis sources import `coriolis-data/dist` and React. The data
  // package lives in the cloned coriolis-data repo, and the React components
  // are never rendered by this API, so map both to local files.
  alias: {
    'coriolis-data/dist': path.join(root, 'coriolis-data/dist/index.js'),
    react: path.join(root, 'shims/react.js'),
  },
  logLevel: 'info',
});

console.log('API built successfully!');
